name: NetflixMovieCatalog stack build-deploy

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/netflix-movie-catalog:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: ofekhalabi/NetflixInfra.git
          token: ${{ secrets.REPO_TOKEN }}  # The GITHUB_TOKEN secret is a GitHub access token.
          path: ./NetflixInfra
          ref: main  # Explicitly specify the branch

      - name: Update YAML manifests
        run: |
          cd ./NetflixInfra/k8s/NetflixMovieCatalog
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/netflix-movie-catalog:${{ github.run_number }}
          yq e ".spec.template.spec.containers[0].image = \"$IMAGE_NAME\"" -i deployment.yaml


      - name: Commit and Push changes
        run: |
           cd ./NetflixInfra
           git config --local user.email "github@action"
           git config --local user.name "auto-update"
           git add k8s/NetflixMovieCatalog/deployment.yaml
           git commit -m "Update image to $IMAGE_NAME"
           git push origin main
